const TEMP_RECORD_TIME = 1000*60 * 5

const WIND_RECORD_TIME = 1000*60 * 5

const TIME_TO_GO_OFFLINE = 7*24 * 60 * 60 * 1000;

const INTERVAL_TO_CHECK_DEVICE_STATUS = 60 *1000;

const FDI_COUNT_TO_FLAG_DANGER = 5
const RULE30_COUNT_TO_FLAG_DANGER = 5
const TIME_TO_CALL_WEATHER_API = 6 * 60 * 60 * 1000
const CACHE_EXPIRATION_TIME = 5
module.exports={TEMP_RECORD_TIME,WIND_RECORD_TIME,RULE30_COUNT_TO_FLAG_DANGER, FDI_COUNT_TO_FLAG_DANGER,CACHE_EXPIRATION_TIME,TIME_TO_CALL_WEATHER_API}