const TEMP_RECORD_TIME = 60 * 1000

const WIND_RECORD_TIME = 60 * 1000

const TIME_TO_GO_OFFLINE = 7*24 * 60 * 60 * 1000;

const INTERVAL_TO_CHECK_DEVICE_STATUS = 60 *1000;

const FDI_COUNT_TO_FLAG_DANGER = 5
const RULE30_COUNT_TO_FLAG_DANGER = 5

const CACHE_EXPIRATION_TIME = 3600
module.exports={TEMP_RECORD_TIME,WIND_RECORD_TIME,RULE30_COUNT_TO_FLAG_DANGER, FDI_COUNT_TO_FLAG_DANGER,CACHE_EXPIRATION_TIME}